title: "Era Parihar"
description: "Data Scientist specializing in NLP and Generative AI"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://erapariharr.github.io/" # the base hostname & protocol for your site

# GitHub settings
github_username: erapariharr

# Theme settings
theme: minima

# Site settings
name: "Era Parihar"
email: erap@umich.edu & eraparihar@gmail.com
phone: "+1 734-412-9886"
linkedin_username: era-parihar-125a58183
github_username: erapariharr
twitter_username: your_twitter_username # if applicable
google_analytics: UA-XXXXXXXX-X # your Google Analytics tracking ID

# Social links
social_links:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/era-parihar-125a58183/"
  - name: "Email"
    url: "mailto:eraparihar@gmail.com"
  - name: "GitHub"
    url: "https://github.com/erapariharr"

    
# Navigation links
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
<!---  - name: "My Journey"
    url: "/myjourney"  -->   
  - name: "Resume"
    url: "/myresume" 
  - name: "Projects"
    url: "/projects"
<!---  - name: "Certifications"
    url: "/certifications"
  - name: "Blog"
    url: "/blog"  -->
  - name: "Course Notes"
    url: "/coursenotes"
  - name: "Contact"
    url: "/contact"  
